[colors.bright]
black = "#666666"
blue = "#387cd3"
cyan = "#3d97e2"
green = "#77b869"
magenta = "#957bbe"
red = "#e8341c"
white = "#bababa"
yellow = "#efd64b"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#e8e41c"
white = "#828482"
yellow = "#efd64b"

[colors.normal]
black = "#000000"
blue = "#1c98e8"
cyan = "#1c98e8"
green = "#68c256"
magenta = "#8e69c9"
red = "#e8341c"
white = "#bababa"
yellow = "#f2d42c"

[colors.primary]
background = "#222324"
foreground = "#bababa"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 9.0

[font.normal]
family = "SauceCodePro Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
action = "SearchBackward"
key = "R"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
decorations_theme_variant = "Dark"
dynamic_title = true

[bell]
animation = "Ease"
