[colors.bright]
black = "#b4b4b4"
red = "#ff1e00"
green = "#2eff00"
yellow = "#ffff00"
blue = "#46beff"
magenta = "#957bbe"
cyan = "#00ffff"
white = "#ffffff"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#e8e41c"
white = "#828482"
yellow = "#efd64b"

[colors.normal]
black = "#000000"
red = "#e22c14"
green = "#68c256"
yellow = "#f2d42c"
blue = "#1d85e4"
magenta = "#8e69c9"
cyan = "#11d1d1"
white = "#cccccc"

[colors.primary]
background = "#222324"
foreground = "#ffffff"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 9.0

[font.normal]
family = "SauceCodePro Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
action = "SearchBackward"
key = "R"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
decorations_theme_variant = "Dark"
dynamic_title = true

[bell]
animation = "Ease"
