local C = {
  ["SpecialKey"]              = { ctermfg = 75 , fg = '#569cd6' },
  ["EndOfBuffer"]             = {},
  ["NonText"]                 = { ctermfg = 240, fg = '#5a5a5a' },
  ["Directory"]               = { ctermfg = 75 , fg = '#569cd6' },
  ["ErrorMsg"]                = { ctermfg = 9  , fg = 'LightRed' },
  ["IncSearch"]               = { ctermbg = 58 , bg = '#4b5632' },
  ["Search"]                  = { ctermbg = 94 , bg = '#773800' },
  ["ModeMsg"]                 = { ctermfg = 188, ctermbg = 235,
                                  fg = '#d4d4d4', bg = '#252526' },
  ["LineNr"]                  = { fg = 'Gray' },
  ["CursorLineNr"]            = { ctermfg = 250, ctermbg = 234,
                                  fg = '#bbbbbb', bg = '#1e1e1e' },
  ["Question"]                = { ctermfg = 75,  ctermbg = 234,
                                  fg = '#569cd6', bg = '#1e1e1e' },
  ["VertSplit"]               = { ctermfg = 238, ctermbg = 234,
                                  fg = '#444444', bg = '#1e1e1e' },
  ["Title"]                   = { bold = true },
  ["Visual"]                  = { ctermbg = 24 , bg = '#264f78' },
  ["WarningMsg"]              = { link = 'ErrorMsg' },
  ["WildMenu"]                = { ctermbg = 24 , bg = '#264f78' },
  ["Folded"]                  = { underline = true, ctermfg = 238, ctermbg = 235,
                                  fg = '#3f3f46', bg = '#252526' },
  ["FoldColumn"]              = { ctermfg = 240, ctermbg = 234,
                                  fg = '#5a5a5a', bg = '#1e1e1e' },
  ["DiffAdd"]                 = { ctermfg = 188, ctermbg = 58,
                                  fg = '#d4d4d4', bg = '#4b5632' },
  ["DiffChange"]              = { ctermfg = 188, ctermbg = 24,
                                  fg = '#d4d4d4', bg = '#005f87' },
  ["DiffDelete"]              = { ctermfg = 188, ctermbg = 52,
                                  fg = '#d4d4d4', bg = '#6f1313' },
  ["DiffText"]                = { ctermfg = 234, ctermbg = 117,
                                  fg = '#1e1e1e', bg = '#87d7ff' },
  ["SignColumn"]              = {},
  ["Conceal"]                 = { ctermfg = 188, ctermbg = 234,
                                  fg = '#d4d4d4', bg = '#1e1e1e' },
  ["SpellBad"]                = { undercurl = true, ctermfg = 203, ctermbg = 234,
                                  fg = '#f44747', bg = '#1e1e1e', sp = '#f44747' },
  ["SpellCap"]                = { link = "SpellBad" },
  ["SpellRare"]               = { link = "SpellBad" },
  ["SpellLocal"]              = { link = "SpellBad" },
  ["Pmenu"]                   = { ctermfg = 250, ctermbg = 236,
                                  fg = '#bbbbbb', bg = '#2d2d30' },
  ["PmenuSel"]                = { ctermfg = 250, ctermbg = 24,
                                  fg = '#bbbbbb', bg = '#073655', blend=0 },
  ["PmenuKind"]               = { link = "Pmenu" },
  ["PmenuKindSel"]            = { link = "PmenuSel" },
  ["PmenuExtra"]              = { link = "Pmenu" },
  ["PmenuExtraSel"]           = { link = "PmenuSel" },
  ["PmenuSbar"]               = { ctermbg = 237, bg = "#3d3d40" },
  ["PmenuThumb"]              = { ctermbg = 250, bg = "#bbbbbb" },
  ["TabLine"]                 = { ctermfg = 188, ctermbg = 236,
                                  fg = '#d4d4d4', bg = '#2d2d2d' },
  ["TabLineSel"]              = { ctermfg = 188, ctermbg = 234,
                                  fg = '#d4d4d4', bg = '#1e1e1e' },
  ["TabLineFill"]             = { ctermfg = 188, ctermbg = 235,
                                  fg = '#d4d4d4', bg = '#252526' },
  ["CursorLine"]              = { ctermbg = 235, bg = '#222222' },
  ["NormalFloat"]             = { link = "Pmenu" },
  ["Cursor"]                  = { ctermfg = 239, ctermbg = 145,
                                  fg = '#51504f', bg = '#aeafad' },
  ["Character"]               = { ctermfg = 173, fg = '#ce9178' },
  ["Constant"]                = { ctermfg = 75 , fg = '#569cd6' },
  ["Number"]                  = { ctermfg = 151, fg = '#b5cea8' },
  ["Boolean"]                 = { ctermfg = 75 , fg = '#569cd6' },
  ["Conditional"]             = { ctermfg = 176, fg = '#c586c0' },
  ["Statement"]               = { ctermfg = 176, fg = '#c586c0' },
  ["Repeat"]                  = { ctermfg = 176, fg = '#c586c0' },
  ["Label"]                   = { ctermfg = 176, fg = '#c586c0' },
  ["Keyword"]                 = { ctermfg = 176, fg = '#c586c0' },
  ["Exception"]               = { ctermfg = 176, fg = '#c586c0' },
  ["Include"]                 = { ctermfg = 176, fg = '#c586c0' },
  ["PreProc"]                 = { ctermfg = 176, fg = '#c586c0' },
  ["Define"]                  = { ctermfg = 176, fg = '#c586c0' },
  ["Macro"]                   = { ctermfg = 176, fg = '#c586c0' },
  ["PreCondit"]               = { ctermfg = 176, fg = '#c586c0' },
  ["StorageClass"]            = { ctermfg = 75 , fg = '#569cd6' },
  ["Type"]                    = { ctermfg = 75 , fg = '#569cd6' },
  ["Structure"]               = { ctermfg = 75 , fg = '#569cd6' },
  ["Typedef"]                 = { ctermfg = 75 , fg = '#569cd6' },
  ["Tag"]                     = { ctermfg = 188, fg = '#d4d4d4' },
  ["Special"]                 = { ctermfg = 179, fg = '#d7ba7d' },
  ["SpecialChar"]             = { ctermfg = 188, fg = '#d4d4d4' },
  ["SpecialComment"]          = { ctermfg = 65 , fg = '#6a9955' },
  ["Debug"]                   = { ctermfg = 188, fg = '#d4d4d4' },
  ["Ignore"]                  = { ctermfg = 234, fg = '#1e1e1e' },
  ["DiagnosticFloatingError"] = { link = "DiagnosticVirtualTextError" },
  ["Comment"]                 = { ctermfg = 65 , fg = '#6a9955' },
  ["@variable"]               = { ctermfg = 117, fg = '#9cdcfe' },
  ["@variable.builtin"]       = { ctermfg = 117, fg = '#9cdcfe' },
  ["@constant"]               = { ctermfg = 187, fg = '#dcdcaa' },
  ["@constant.builtin"]       = { link = "Constant" },
  ["@label"]                  = { ctermfg = 117, fg = '#9cdcfe' },
  ["String"]                  = { ctermfg = 173, fg = '#ce9178' },
  ["@string.escape"]          = { ctermfg = 179, fg = '#d7ba7d' },
  ["@boolean"]                = { ctermfg = 75 , fg = '#569cd6' },
  ["@type"]                   = { ctermfg = 43 , fg = '#4ec9b0' },
  ["@type.builtin"]           = { link = "Type" },
  ["@attribute"]              = { ctermfg = 43 , fg = '#4ec9b0' },
  ["@property"]               = { ctermfg = 117 , fg = '#9cdcfe' },
  ["Identifier"]              = { ctermfg = 117 , fg = '#9cdcfe' },
  ["Function"]                = { ctermfg = 187 , fg = '#dcdcaa' },
  ["@function.builtin"]       = { link = "Function" },
  ["@constructor"]            = { ctermfg = 43 , fg = '#4ec9b0' },
  ["@operator"]               = { ctermfg = 188 , fg = '#d4d4d4' },
  ["Operator"]                = { ctermfg = 188 , fg = '#d4d4d4' },
  ["@keyword"]                = { ctermfg = 75 , fg = '#569cd6' },
  ["Delimiter"]               = { ctermfg = 188 , fg = '#d4d4d4' },
  ["@punctuation.special"]    = { link = "Delimiter" },
  ["Todo"]                    = { ctermbg = 237 , bg = '#373737' },
  ["@tag"]                    = { ctermfg = 75 , fg = '#569cd6' },
  ["@constant.macro"]         = { ctermfg = 43 , fg = '#4ec9b0' },
  ["@function.method"]        = { link = "Function" },
  ["@variable.parameter"]     = { link = "Identifier" },
  ["@type.definition"]        = { link = "Typedef" },
  ["MatchParen"]              = { ctermbg = 239 , bg = '#51504f' },
  ["Error"]                   = { undercurl = true, ctermfg = 203, ctermbg = 234,
                                  fg = '#f44747', bg = '#1e1e1e', sp = '#f44747' },
  ["@markup.raw"]             = { link = "Comment" },
  ["@markup.link.url"]        = { link = "Underlined" },
  ["@keyword.directive"]      = { link = "PreProc" },
  ["@function.macro"]         = { link = "Function" },
  ["@variable.member"]        = { link = "Identifier" },
  ["@keyword.conditional"]    = { link = "Conditional" },
  ["@keyword.repeat"]         = { link = "Repeat" },
  ["@keyword.exception"]      = { link = "Exception" },
  ["@keyword.storage"]        = { link = "StorageClass" },
  ["@keyword.import"]         = { link = "Include" },
  ["@keyword.debug"]          = { link = "Debug" },
  ["StatusLineTerm"]          = { link = "StatusLine" },
  ["StatusLineTermNC"]        = { link = "StatusLineNC" },
  ["MessageWindow"]           = { link = "Pmenu" },
  ["PopupNotification"]       = { link = "Todo" },
  ["ToolbarButton"]           = { bold = true, ctermfg = 230, ctermbg = 236,
                                  fg = '#fbf1c7', bg = '#303030' },
  ["ToolbarLine"]             = {},
}

return C
