# Set XDG user directories if not already set

if [ -z "$XDG_CONFIG_HOME" ]; then
    export XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$XDG_CACHE_HOME" ]; then
    export XDG_CACHE_HOME=$HOME/.cache
fi

if [ -z "$XDG_DATA_HOME" ]; then
    export XDG_DATA_HOME=$HOME/.local/share
fi

if [ -z "$XDG_STATE_HOME" ]; then
    export XDG_STATE_HOME=$HOME/.local/state
fi

if [ -f "${XDG_CONFIG_HOME}/zsh/init.zsh" ]; then
    source "${XDG_CONFIG_HOME}/zsh/init.zsh"
elif [ -f "${HOME}/.zsh/init.zsh" ]; then
    source "${HOME}/.zsh/init.zsh"
else
    echo "[!] Could not source zsh directory."
fi
