export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state

if [ -f "${XDG_CONFIG_HOME}/zsh/init.zsh" ]; then
    source "${XDG_CONFIG_HOME}/zsh/init.zsh"
elif [ -f "${HOME}/.zsh/init.zsh" ]; then
    source "${HOME}/.zsh/init.zsh"
else
    echo "[!] Could not source zsh directory."
fi
